// Code generated by MockGen. DO NOT EDIT.
// Source: internal/controller/http/server.go

// Package http is a generated GoMock package.
package http

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	websocket "github.com/gorilla/websocket"
)

// MockWsNotificationsService is a mock of WsNotificationsService interface.
type MockWsNotificationsService struct {
	ctrl     *gomock.Controller
	recorder *MockWsNotificationsServiceMockRecorder
}

// MockWsNotificationsServiceMockRecorder is the mock recorder for MockWsNotificationsService.
type MockWsNotificationsServiceMockRecorder struct {
	mock *MockWsNotificationsService
}

// NewMockWsNotificationsService creates a new mock instance.
func NewMockWsNotificationsService(ctrl *gomock.Controller) *MockWsNotificationsService {
	mock := &MockWsNotificationsService{ctrl: ctrl}
	mock.recorder = &MockWsNotificationsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWsNotificationsService) EXPECT() *MockWsNotificationsServiceMockRecorder {
	return m.recorder
}

// HandleConnection mocks base method.
func (m *MockWsNotificationsService) HandleConnection(ctx context.Context, userEmail string, connection *websocket.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleConnection", ctx, userEmail, connection)
}

// HandleConnection indicates an expected call of HandleConnection.
func (mr *MockWsNotificationsServiceMockRecorder) HandleConnection(ctx, userEmail, connection interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleConnection", reflect.TypeOf((*MockWsNotificationsService)(nil).HandleConnection), ctx, userEmail, connection)
}

// MockWebSocketUpgrader is a mock of WebSocketUpgrader interface.
type MockWebSocketUpgrader struct {
	ctrl     *gomock.Controller
	recorder *MockWebSocketUpgraderMockRecorder
}

// MockWebSocketUpgraderMockRecorder is the mock recorder for MockWebSocketUpgrader.
type MockWebSocketUpgraderMockRecorder struct {
	mock *MockWebSocketUpgrader
}

// NewMockWebSocketUpgrader creates a new mock instance.
func NewMockWebSocketUpgrader(ctrl *gomock.Controller) *MockWebSocketUpgrader {
	mock := &MockWebSocketUpgrader{ctrl: ctrl}
	mock.recorder = &MockWebSocketUpgraderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebSocketUpgrader) EXPECT() *MockWebSocketUpgraderMockRecorder {
	return m.recorder
}

// Upgrade mocks base method.
func (m *MockWebSocketUpgrader) Upgrade(w http.ResponseWriter, r *http.Request, responseHeader http.Header) (*websocket.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upgrade", w, r, responseHeader)
	ret0, _ := ret[0].(*websocket.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upgrade indicates an expected call of Upgrade.
func (mr *MockWebSocketUpgraderMockRecorder) Upgrade(w, r, responseHeader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upgrade", reflect.TypeOf((*MockWebSocketUpgrader)(nil).Upgrade), w, r, responseHeader)
}
