// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/contracts.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/mwsbkru/evrone-go-final/internal/entity"
)

// MockNotificationsObserver is a mock of NotificationsObserver interface.
type MockNotificationsObserver struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationsObserverMockRecorder
}

// MockNotificationsObserverMockRecorder is the mock recorder for MockNotificationsObserver.
type MockNotificationsObserverMockRecorder struct {
	mock *MockNotificationsObserver
}

// NewMockNotificationsObserver creates a new mock instance.
func NewMockNotificationsObserver(ctrl *gomock.Controller) *MockNotificationsObserver {
	mock := &MockNotificationsObserver{ctrl: ctrl}
	mock.recorder = &MockNotificationsObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationsObserver) EXPECT() *MockNotificationsObserverMockRecorder {
	return m.recorder
}

// StartListening mocks base method.
func (m *MockNotificationsObserver) StartListening(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartListening", ctx)
}

// StartListening indicates an expected call of StartListening.
func (mr *MockNotificationsObserverMockRecorder) StartListening(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartListening", reflect.TypeOf((*MockNotificationsObserver)(nil).StartListening), ctx)
}

// Subscribe mocks base method.
func (m *MockNotificationsObserver) Subscribe(subscriber NotificationsSubscriber, terminator Terminator) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", subscriber, terminator)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockNotificationsObserverMockRecorder) Subscribe(subscriber, terminator interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockNotificationsObserver)(nil).Subscribe), subscriber, terminator)
}

// MockNotificationsProcessor is a mock of NotificationsProcessor interface.
type MockNotificationsProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationsProcessorMockRecorder
}

// MockNotificationsProcessorMockRecorder is the mock recorder for MockNotificationsProcessor.
type MockNotificationsProcessorMockRecorder struct {
	mock *MockNotificationsProcessor
}

// NewMockNotificationsProcessor creates a new mock instance.
func NewMockNotificationsProcessor(ctrl *gomock.Controller) *MockNotificationsProcessor {
	mock := &MockNotificationsProcessor{ctrl: ctrl}
	mock.recorder = &MockNotificationsProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationsProcessor) EXPECT() *MockNotificationsProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockNotificationsProcessor) Process(ctx context.Context, notification *entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockNotificationsProcessorMockRecorder) Process(ctx, notification interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockNotificationsProcessor)(nil).Process), ctx, notification)
}

// MockDeadNotificationsProcessor is a mock of DeadNotificationsProcessor interface.
type MockDeadNotificationsProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockDeadNotificationsProcessorMockRecorder
}

// MockDeadNotificationsProcessorMockRecorder is the mock recorder for MockDeadNotificationsProcessor.
type MockDeadNotificationsProcessorMockRecorder struct {
	mock *MockDeadNotificationsProcessor
}

// NewMockDeadNotificationsProcessor creates a new mock instance.
func NewMockDeadNotificationsProcessor(ctrl *gomock.Controller) *MockDeadNotificationsProcessor {
	mock := &MockDeadNotificationsProcessor{ctrl: ctrl}
	mock.recorder = &MockDeadNotificationsProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeadNotificationsProcessor) EXPECT() *MockDeadNotificationsProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockDeadNotificationsProcessor) Process(notification *entity.Notification, err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", notification, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockDeadNotificationsProcessorMockRecorder) Process(notification, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockDeadNotificationsProcessor)(nil).Process), notification, err)
}

// MockWsNotificationsReceiver is a mock of WsNotificationsReceiver interface.
type MockWsNotificationsReceiver struct {
	ctrl     *gomock.Controller
	recorder *MockWsNotificationsReceiverMockRecorder
}

// MockWsNotificationsReceiverMockRecorder is the mock recorder for MockWsNotificationsReceiver.
type MockWsNotificationsReceiverMockRecorder struct {
	mock *MockWsNotificationsReceiver
}

// NewMockWsNotificationsReceiver creates a new mock instance.
func NewMockWsNotificationsReceiver(ctrl *gomock.Controller) *MockWsNotificationsReceiver {
	mock := &MockWsNotificationsReceiver{ctrl: ctrl}
	mock.recorder = &MockWsNotificationsReceiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWsNotificationsReceiver) EXPECT() *MockWsNotificationsReceiverMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockWsNotificationsReceiver) Subscribe(receivedNotificationProcessor ReceivedNotificationProcessor, wsConnectionTerminator WsConnectionTerminator) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", receivedNotificationProcessor, wsConnectionTerminator)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockWsNotificationsReceiverMockRecorder) Subscribe(receivedNotificationProcessor, wsConnectionTerminator interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockWsNotificationsReceiver)(nil).Subscribe), receivedNotificationProcessor, wsConnectionTerminator)
}

// ReceiveNotifications mocks base method.
func (m *MockWsNotificationsReceiver) ReceiveNotifications(ctx context.Context, userEmail string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReceiveNotifications", ctx, userEmail)
}

// ReceiveNotifications indicates an expected call of ReceiveNotifications.
func (mr *MockWsNotificationsReceiverMockRecorder) ReceiveNotifications(ctx, userEmail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveNotifications", reflect.TypeOf((*MockWsNotificationsReceiver)(nil).ReceiveNotifications), ctx, userEmail)
}
